#!/bin/bash
os=`uname`
echo $os

exclude="--exclude-from exclude.linux"
if [[ "$os" == "FreeBSD" ]]; then
	exclude="--exclude-from exclude.freebsd"
fi

rsync -rv --delete --delete-excluded $exclude .vim .vimrc ~

if [[ "$os" == "Darwin" ]]; then
    echo "I'm a MAC..."
    sed -i'' -e 's/set guifont=.*/set guifont=DejaVu\\ Sans\\ Mono\\ for\\ Powerline:h11/' ~/.vimrc
fi

. scripts/make
